import type { Metadata } from "next";
import "./globals.css";
import RainbowKitProviderWrapper from "../providers/RainbowKitProvider";
import Footer from "@/components/Footer";
import { cn, poppins } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "antialiased bg-gradient-to-b from-[#FFC882] to-[#FDE0B9]",
          poppins.className
        )}
      >
        <RainbowKitProviderWrapper>
          <div className="mx-auto min-h-screen bg-[#FFC882] relative overflow-hidden">
            {children}
            <Footer />
          </div>
        </RainbowKitProviderWrapper>
      </body>
    </html>
  );
}
